### ISSUE TITLE
Vee and Daneel start without their Siege Engines

### ISSUE THREAD

**Issue by cinnamon189** [vcmi-mods/forge#11]
Vee and Daneel start without the respective Siege Engines they are specialising in. Apparently, the only way to avoid this is to have the HotA Unrandomized start sub-mod enabled. That seems unintended, because playing without this mod would mean a severe handicap for these heroes. Please make sure they always start with their respective Siege Engines.

**Comment by misiokles** [comment]
Gift delivery spell comes from Asylum town. Will check it.

**Comment by misiokles** [comment]
Yeah, Forge mod is older than HotA Unrandomized start option. I can add such option to mod.json as default, but I must test how this will influence other mods.

**Comment by misiokles** [comment]
Added Less random start submod for 2.2.3 version.

**Comment by cinnamon189** [comment]
As far as I can tell, these two Heroes start without their Siege Engines regardless of chance, so a "Less random start" mod may be confusing here. I remember Christian and other original Heroes from HoMM III always start with the Siege Engine they specialise in – maybe better to adapt this behaviour for these two Heroes than to create a new submod? Also to avoid unforeseen interactions with other mods.
