### ISSUE TITLE
wrong icon of creature speciality

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi-mods/forge#6]
![Screenshot 2022-09-23 at 17 16 54](https://user-images.githubusercontent.com/1557784/191985347-43e79b00-1e02-40eb-b6ae-2a0f670077c0.png)

**Comment by kambala-decapitator** [comment]
seems all icons are broken:

![Screenshot 2022-09-24 at 13 27 57](https://user-images.githubusercontent.com/1557784/192099493-d2a93d0a-3428-46e4-9c9a-feab7b850d6a.png)
![Screenshot 2022-09-24 at 13 34 03](https://user-images.githubusercontent.com/1557784/192099495-4258fcbc-fea2-4b8c-a1b6-9f2c85bfb069.png)
![Screenshot 2022-09-24 at 15 19 21](https://user-images.githubusercontent.com/1557784/192099497-0912a839-7cb4-4bdf-96be-b6a3e7776046.png)

**Comment by misiokles** [comment]
I can't confirm that...

**Comment by kambala-decapitator** [comment]
yes, seems fine now
